### ISSUE TITLE
array_histogram

### ISSUE THREAD

**Issue by aeosynth** [Biribiri/K-R#1]
is there any reason you use both `i` and `n` to keep track of loops? why do you declare `i` twice?

```
while( (c = getchar()) != EOF){
    ++letters[c - 'a'];
    if(letters[c - 'a'] > max)
            max = (int)letters[c - 'a'];
}
```

you can shave a line:

```
while( (c = getchar()) != EOF){
    if(++letters[c - 'a'] > max)
            max = (int)letters[c - 'a'];
}
```

when I ran your program, a curious thing happened: a string of newlines cleared my terminal's buffer.

you aren't checking if `c` is from a-z. if it is `' '` (ASCII 10), subtracting `'a'` (ASCII 97) gives -87. you increment a piece of memory 87 blocks _before_ the letters array starts, and use that value in the `max` algorithm. this will give you bogus results, as well as potentially crashing your computer.

moving on:

wtf is that `(int)` casting for?

aesthetics: `putchar('\n')` seems nicer than `printf("\n")`.

```
    if(i < 10)
        printf(" %d ", letters[i]);
    else
        printf(" %d ", letters[i]);
```

you didn't finish your thought.

you don't print a final newline.

**Comment by Biribiri** [comment]
Thanks, I didn't see that I could have saved the line by removing ++letters.

Oh thank you, I was wondering why it wasn't running. Also added checks for upper and lower case, well I just converted all input to lower case.

What did you mean by "you increment a piece of memory 87 blocks before the letters array starts, and use that value in the max algorithm"?

I'm not sure why I had the (int) cast, removed.

putchar() does look nicer than printf(). Will keep in mind.

**Comment by aeosynth** [comment]
arrays are just sequential blocks of memory. when you declare `int array[10]`, you're reserving ten blocks (bytes?) of memory. `array[0]` will access the first reserved block, `array[1]` the second, and so on.

however, arrays can also have negative indices. `array[-1]` access the block immediately before `array[0]`. this block has not been reserved, and could be in use by another program; we have no information about it. changing this block could adversely affect the program (if any) that is using it.

**Comment by Biribiri** [comment]
I see, but where am I doing that?

**Comment by aeosynth** [comment]
you aren't anymore, but you were when you were doing `letters[c - a]` when `c` was `' '`.

**Comment by aeosynth** [comment]
https://github.com/Biribiri/K-R/blob/master/Ch.1/array_histogram.c#L17

```
    if( ((int)c >= 97 && (int)c <= 123) && ++letters[c - 'a'] > max)
```

97 and 123 are magic numbers; this is more readable:

```
    if( ((int)c >= 'a' && (int)c <= 'z') && ++letters[c - 'a'] > max)
```

again, why are you (int) casting?

**Comment by Biribiri** [comment]
Ohhh, I get it. Thanks again.

**Comment by Biribiri** [comment]
Because I'm an idiot, that's why. I'm just used to letters being chars not int. Fixed

Isn't c an int, so wouldn't you be comparing # to a letter?

**Comment by aeosynth** [comment]
single quotes returns the numeric value of the character, so no, it's still # vs #.

**Comment by Biribiri** [comment]
Didn't know that, thanks for explaining.
