### ISSUE TITLE
char_arrays80

### ISSUE THREAD

**Issue by aeosynth** [Biribiri/K-R#3]
I originally buffered the entire line, up to `MAXLINE - 1` characters, but after looking at your code, I rewrote my answer to buffer the minimum amount of text - [17.c](https://github.com/aeosynth/K-R/blob/master/ch1/17.c).

you have two calls to `getchar`, that was a bit of a mindfuck. I inlined everything.

**Comment by aeosynth** [comment]
also you should probably remove your debugging code before you publish

**Comment by Biribiri** [comment]
C, more of a mindfuck than nge. I should start commenting my code, I had to stare at it for a good 5 min before I remembered why I had two getchar() calls.

I like the way you did yours, but find mine easier to read. Although without functions, I would prefer your way.

What's with passing int argc, const char *argv[] in main?

Oh shit didn't even realize I left that there, I typically remove all debug code before saving the finished copy.

**Comment by aeosynth** [comment]
> What's with passing int argc, const char *argv[] in main?

i use [snipmate](https://github.com/msanders/snipmate.vim), a vim plugin. I just type `main<Tab>` and the plugin expands that to

```
int main(int argc, const char *argv[]) {

  return 0;
}
```

w/ the cursor at the blank line. `argc` = argument count, `argv` = argument value. eventually we'll write programs that take arguments.

**Comment by Biribiri** [comment]
Oh that's cool.
