### ISSUE TITLE
entab

### ISSUE THREAD

**Issue by aeosynth** [Biribiri/K-R#5]
doesn't work

edit: but it's a neat idea - buffering the least amount possible. I rewrote [21.c](https://github.com/aeosynth/K-R/blob/master/ch1/21.c) to use that idea. [before](https://github.com/aeosynth/K-R/blob/74fd0303fc2132082588e61b978005a90451314f/ch1/21.c).

**Comment by Biribiri** [comment]
What doesn't work?

**Comment by aeosynth** [comment]
copy paste this

```
a b                     c
```

**Comment by aeosynth** [comment]
storing spaces as a string seems lame; why not just count the number of blanks, and then loop `putchar`?

**Comment by Biribiri** [comment]
Because I forgot putchar() even existed. Thanks, and should be fixed now.

**Comment by aeosynth** [comment]
still doesn't work. are you testing this?

**Comment by Biribiri** [comment]
no you're testing for me. whats wrong this time

**Comment by aeosynth** [comment]
it doesn't actually replace blanks with tabs

```
this                  is a test
```

**Comment by Biribiri** [comment]
I don't get why it's broken. Screw it, watching nasl.

**Comment by aeosynth** [comment]
[DISAPPOINTED](http://www.youtube.com/watch?v=tojt8QhKrrk)

**Comment by Biribiri** [comment]
But nasl, well it was a disappointment anyways. WhiteRa lost :( who am I supposed to cheer for now.

I would work on it but I don't even know why it's failing. 

swift edit: I think I get why.
Nope, still confused.
