### ISSUE TITLE
a.exe

### ISSUE THREAD

**Issue by aeosynth** [Biribiri/K-R#6]
do you really need to track it with git?

**Comment by Biribiri** [comment]
No, but it's in my Ch.1 folder and git automatically pushes it. And too lazy to remove it before pushing.

**Comment by aeosynth** [comment]
You could remove it now and commit the removal.
On Jul 8, 2011 8:50 PM, "Biribiri" <
reply@reply.github.com>
wrote:

**Comment by Biribiri** [comment]
I'll be sure to remove it before finishing up with ch. 1 entab looks like the last thing i need to fix.

**Comment by aeosynth** [comment]
man git-stash
